### ISSUE TITLE
lkkl;k

### ISSUE THREAD

**Issue by akila-sama** [akila-sama/akila_plugin#3]

**Comment by uvesh-bhatti** [comment]
- please check below meta box code it not work properly.


![Screenshot from 2024-05-13 17-09-14](https://github.com/akila-sama/akila_plugin/assets/142868436/077254a4-257e-44f8-be5d-bafab6dc33bb)


- please recheck the register post type when it create the one post type so it the view time it not found in front side.

**Comment by akila-sama** [comment]
issue solve
